'use client';
import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown, FileText, Shield, RotateCcw } from 'lucide-react';
import AppLayout from '../../components/layout/AppLayout';

const PARTS = [
    {
        id: 'terms',
        part: 'Part – I',
        title: 'Terms & Conditions',
        icon: FileText,
        color: '#ef3837',
        sections: [
            {
                title: 'Introduction & Scope',
                content: [
                    'JK India eAgriTech Ltd. (formerly known as JK Sugars and Commodities Pvt. Ltd.), an enterprise of Indian origin (hereinafter "eBuySugar"), operates a business-to-business sugar commodities trading platform through www.ebuysugar.com (the "Site").',
                    'JK India eAgriTech Ltd. provides this Site to you subject to the following conditions. By visiting www.ebuysugar.com, which includes the website as well as the Mobile Application or any other electronic platform provided by eBuySugar, you accept these conditions.',
                    'These "Conditions of Usage" constitute an electronic record within the meaning of applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures.',
                    '1. eBuySugar operates a B2B sugar commodities trading platform. Sugar can be bought and sold online using the Platform\'s buying/selling option. Users can buy/sell any quantity of Sugar, Khandsari Sugar, Jaggery & Jaggery Powder on the Platform, subject to fulfilment of other stipulated conditions.',
                    '2. These Terms of User Agreement govern your use of the website and services provided by eBuySugar. By accessing or using the website, you agree to be bound by all terms and conditions of this agreement.',
                    '3. If you do not agree to this agreement, then do not browse or use the website or Mobile Apps.',
                    '4. Any transactional risks associated with the purchase or sale of products offered through the website shall be fully borne by you as a user.',
                    '5. eBuySugar is the owner of this website and has full right to manage and operate it.',
                    '6. The user accessing this website shall be 18 years of age or above and must have the right, authority, and capacity to use the Website.',
                    '7. The Website may use cookies and the user agrees to use cookies in accordance with the Company\'s Privacy Policy.',
                    '10. Your use of the Website is governed by this Agreement. You may not co-brand, frame, or hyper-link to this Website without prior written permission of eBuySugar.',
                    '12. eBuySugar reserves the right to change or discontinue any aspect of the Website at any time. eBuySugar may also modify or amend this agreement at any time.',
                    '13. eBuySugar reserves the right to terminate User\'s access to the Website at any time, for any reason without notice.',
                ],
            },
            {
                title: 'Procedure for Buyers & Sellers',
                content: [
                    'Buyer & Seller (hereinafter "Users") shall be registered members of www.ebuysugar.com for sugar commodity, having necessary licenses and statutory approvals. JK India eAgriTech Ltd. shall be counterparty to all trades. The transactions shall be on a Principal to Principal basis.',
                    '16.1 Pre-Requisites for e-trade: User means an individual or legal entity having necessary licenses and statutory approvals to transact in sugar commodity.',
                    '16.2 E-trade Timing: The e-trade timing on www.ebuysugar.com will be between 10 a.m. to 8 p.m. on all working days except Sunday.',
                    '16.3 Contract Specification: When the seller publishes an offer, the following will be specified: Sugar mill\'s name, delivery location, grade, season, payment and lifting date, quantity, GST & PAN numbers, EMD, payment bank details and other special terms.',
                    '16.4 Variation: At the time of actual physical delivery, there may be a variation in colour, crystal size and traded quantity on account of storage gain/loss.',
                    '16.5 Responsibility to Honour Terms: The responsibility to honour the terms of trade match confirmation rests with the transacting parties.',
                    '16.6 Post Approval of e-trade: Once accepted, both parties are bound. The User (buyer) agrees to purchase and pay for the confirmed quantity. The User (seller) is fully liable to fulfil the delivery of committed quantity and quality.',
                    '16.7 Charges: The User (buyer) may be required to pay logistics, lifting, loading, weighing and other charges at the delivery location.',
                    '16.8 Early Margin Deposit (EMD): eBuySugar will levy EMD on the quantity to be transacted. Every registered user will have an allotted e-wallet.',
                    '16.9 Transaction Processing: Upon matching of an order, confirmation shall be sent by eBuySugar to both User (Seller) and User (Buyer). The transaction price shall include eBuySugar\'s profit margin for the buyer and a corresponding deduction for the seller.',
                    '16.10 Force Majeure: Should any force majeure circumstances (Act of God, pandemic, war, government restrictions, etc.) occur, the stipulated performance period shall be extended for as long as these circumstances prevail.',
                ],
            },
            {
                title: 'User Content',
                content: [
                    '17.1 As a User, you are fully responsible for any material or content you post on the Website including text, images, graphics, email messages, data and proprietary information. eBuySugar does not systematically monitor, edit or control User Content.',
                    '17.2 eBuySugar reserves the right to verify/screen User Content and may delete, move or edit User Content as well as suspend or terminate any User\'s access.',
                    '17.3 Users undertake not to post unlawful, false, threatening, abusive, harmful, harassing, libelous, pornographic or indecent content; not to infringe copyright or trademarks; not to impersonate any person; and not to transmit malware or viruses.',
                    '17.4 If a user breaches these terms and posts misleading or offensive content, in addition to account cancellation, the user shall bear all risks associated with such User Content.',
                    '17.5 If a user disassociates with eBuySugar, the data shared on the website will not be claimed back. eBuySugar will not use the data for any wrongful means.',
                ],
            },
            {
                title: 'eBuySugar Content & Intellectual Property',
                content: [
                    '18.1 The eBuySugar content is proprietary information. It may not be copied, distributed, republished, uploaded or transmitted in any way without prior written consent of eBuySugar. You may download or print for personal/business internal use only.',
                    '18.2 Trademarks, service marks and logos on this website are the property of eBuySugar or the party that provided the content.',
                    '22.1 As a User, you represent that you own all rights or have acquired necessary authorisation for User Content posted on the Website.',
                    '22.2 You grant to eBuySugar a perpetual royalty-free non-exclusive license to reproduce, modify, translate, make available, distribute and sub-license any User Content you post on the Website.',
                ],
            },
            {
                title: 'Registration, Conditions & Fees',
                content: [
                    '19.1 There are two types of Registered Members: "Seller" and "Buyer".',
                    '19.2 eBuySugar charges Profit Margin as a percentage of transaction value from both parties. A User is also required to place Early Margin Deposit (EMD) before execution. Upon closure of the transaction, the EMD shall be credited back to the respective Registered Member.',
                    '19.3 Registration fees are paid through debit card, credit card, UPI, wire transfer or any other electronic payment method.',
                    '19.4 Once a transaction is confirmed, it shall be segregated into 2 distinct transactions: (1) between User (Seller) and eBuySugar as counterparty Buyer, and (2) between eBuySugar as Seller and User (Buyer). Both transactions are on a Principal to Principal basis.',
                    '19.5 Counterparty to the trade shall remain anonymous. eBuySugar reserves the right to accept or reject a user from becoming a registered user.',
                    '19.6 Registration shall become effective after eBuySugar is satisfied by its verification process.',
                    '19.7 eBuySugar does not refund membership fees except in cases involving fraudulent transactions.',
                    '19.8 You are fully responsible for maintaining your password and not revealing it to any third party.',
                    '19.9 Your registration will be automatically renewed at the anniversary date unless you notify eBuySugar otherwise.',
                ],
            },
            {
                title: 'Trading Transactions & Liability',
                content: [
                    '20.1 eBuySugar provides an online platform for exchange of trade information between Sugar Manufacturers/Traders without indulging in e-commerce activities.',
                    '20.2 All transactions are on a Principal to Principal basis. eBuySugar shall act as Principal in all transactions.',
                    '20.3 Each user acknowledges that it is fully assuming the risks of conducting purchase/sale transactions. Transaction Risks include misrepresentation, fraudulent schemes, unsatisfactory quality, failure to meet specifications, and transportation accidents.',
                    '20.4 In the event of a dispute, the User agrees to indemnify and hold eBuySugar harmless against any liability, loss, damage, cost or expense arising from such transaction or dispute.',
                    '21. User shall indemnify eBuySugar from any claim arising out of user\'s use or conduct of the website. eBuySugar may disclose personal information if required by law, to protect its rights, or to enforce terms.',
                    '24.1 – 24.6 The information on this site is provided "as is" without warranties. eBuySugar shall not be liable for any damages, direct or indirect, resulting from the use or inability to use the website. eBuySugar\'s liability shall at no time exceed the yearly cost of a Member\'s registration fees.',
                ],
            },
            {
                title: 'Termination & Applicable Law',
                content: [
                    '27.1 A Registered Member\'s membership may be terminated immediately upon receipt of written notice in the following circumstances: if insolvency proceedings are initiated; or if the member fails to comply with any material term of this agreement.',
                    '27.2 eBuySugar may terminate a Registered Member\'s membership at its discretion if such continued membership may be prejudicial to eBuySugar\'s business or reputation.',
                    '28.1 Upon termination, a Registered Member\'s membership shall immediately cease to have effect. eBuySugar shall delete such user content preferably within three weeks.',
                    '28.2 Termination may result in permanent loss of all information associated with your account. eBuySugar shall not be liable for any termination of your account.',
                    '35.1 The laws of India, without regard to principles of conflict of laws, will govern this agreement and any dispute.',
                    '35.2 Any claim or dispute shall be resolved by mediation/conciliation, failing which by arbitration in accordance with the Arbitration and Conciliation Act, 1996. The seat of arbitration shall be Kolhapur.',
                    '35.3 Claims may be brought only on your own behalf. Neither you nor eBuySugar will participate in class action or class-wide arbitration.',
                    '37. The Courts of Kolhapur, Maharashtra shall have exclusive jurisdiction to adjudicate upon any claims arising from or relating to this Agreement.',
                    '38. This Agreement shall be governed by the laws of India.',
                ],
            },
        ],
    },
    {
        id: 'privacy',
        part: 'Part – II',
        title: 'Privacy Policy',
        icon: Shield,
        color: '#7c3aed',
        sections: [
            {
                title: 'Introduction & Scope of Privacy Policy',
                content: [
                    '1.1 This Privacy Policy provides eBuySugar\'s policies and procedures with respect to the collection and use of your Personally Identifiable Information (PII) as a User of the Website.',
                    '1.2 By accepting the Terms and Conditions (Part I) and this Privacy Policy, you consent to the transfer of your PII data to us, where your data will be subject to Indian law.',
                    '1.3 eBuySugar places the highest priority on online privacy.',
                    '2.1 PII is personally identifiable information such as your full name, postal address, e-mail address, phone number and license details, and includes wallet information and billing records.',
                    '2.2 Publicly available information, such as a public directory listing of your name, address, telephone number, is not considered PII.',
                ],
            },
            {
                title: 'Collection and Use of Your PII',
                content: [
                    '3.1 You may browse through the Website without registering. If you decide to become a Registered Member, you will be required to provide PII including contact information and business profile.',
                    '3.3 Information containing PII may also be collected to complement information obtained by a business partner or third party.',
                    '3.4 As a Registered Member, you understand that all PII entered on the Website upon registration may be posted and made available to other users.',
                    '3.5 Payment information (credit/debit card, bank details) is accessible only to parties responsible for processing your registration or orders.',
                    '3.7 The Website collects certain technical data including your IP address, domain, and web browser information to create broad demographic summaries.',
                    '3.8 Our Website uses cookies and pixel tags. Cookies are small text files transmitted to your computer to recognize repeat users. You can decline cookies via browser settings, but some website features may not operate properly.',
                    '3.9 eBuySugar employs other companies to perform functions on its behalf. Your PII may be disclosed to such individuals, all of whom are required to protect the information consistently with this Policy.',
                    '3.10 eBuySugar may sell or transfer your PII to third parties in connection with sale, purchase, merger, reorganization or dissolution of eBuySugar, provided the third party commits to protect your PII.',
                    '3.11 eBuySugar may disclose PII to unrelated third parties to comply with a legal requirement or court order, or to investigate a possible crime.',
                ],
            },
            {
                title: 'Communications, Security & External Links',
                content: [
                    '6.1 You may elect not to receive updates or notifications from eBuySugar by communicating the same in writing.',
                    '6.2 We may occasionally send promotional emails. You can opt-out on the registration page or in Account Settings.',
                    '6.4 We will send strictly service-related announcements on rare occasions (e.g., maintenance notices). You generally may not opt-out of these communications.',
                    '7.1 We follow generally accepted industry standards to protect personal information. Your password is essential to maintaining security — never disclose it to any third party.',
                    '7.2 No method of transmission over the Internet is 100% secure. eBuySugar cannot guarantee absolute security. We retain PII for the period necessary to fulfil the purposes outlined in this Policy or as required by law.',
                    '7.3 Information submitted to us will be processed in India. By providing personal information to eBuySugar, you expressly consent to the transfer of your information to India.',
                    'External Links: The Website may contain links to Internet sites not operated by eBuySugar. eBuySugar does not control these sites and is not responsible for their content, security or privacy practices.',
                    'Minors: No one under age 18 is allowed to subscribe to our Website or provide any PII.',
                    '10.1 If we change this Policy, we will post the modified Privacy Policy on this Website. Users should visit the Privacy Policy regularly.',
                ],
            },
            {
                title: 'Contact Us',
                isContact: true,
                content: [
                    'eBuySugar — An initiative by JK India eAgriTech Ltd.',
                    '311, Elixa Park, 3rd Floor, Shahupuri, Near Hotel Sayaji, Kolhapur – 416 001 (MH), India',
                    'Tel: 0231-6688888 / 6688889 / 6688890',
                    'Mobile: 09371999101 / 09326999101',
                    'Email: info@ebuysugar.com',
                    'Website: www.ebuysugar.com',
                    'Privacy Policy — Revised on 07 February 2025.',
                ],
            },
        ],
    },
    {
        id: 'refund',
        part: 'Policy',
        title: 'Refund & Cancellation Policy',
        icon: RotateCcw,
        color: '#059669',
        sections: [
            {
                title: 'No Cancellation Policy',
                content: [
                    'At eBuySugar, we operate as a digital trading platform for bulk sugar procurement. Due to the nature of commodity trading, all confirmed orders are treated as final and binding.',
                    'Once an order is confirmed and payment is successfully processed, the order cannot be cancelled, modified, or reversed under any circumstances. All confirmed orders remain binding with no modification options regardless of the reason.',
                ],
            },
            {
                title: 'No Refunds Policy',
                content: [
                    'eBuySugar maintains a strict no-refund policy. Payments made against confirmed orders are non-refundable, except under specific exceptional circumstances as described below.',
                ],
            },
            {
                title: 'Exceptions to No-Refund Policy',
                content: [
                    'Refunds will only be processed if:',
                    '• eBuySugar is unable to fulfil the order due to supplier failure or stock unavailability.',
                    '• The buyer is charged more than once for the same order due to a technical error.',
                    '• A transaction is completed but the order is not generated because of a system failure.',
                    'In such cases, refunds will be processed to the original payment method within 7–10 business days.',
                ],
            },
            {
                title: 'Disclaimer',
                content: [
                    'The contents of this website do not constitute professional advice or the provision of any kind of services and should not be relied upon as such. eBuySugar does not make any recommendation and assumes no responsibility towards any trading in sugars or commodities done based on the information given in the website. Any such trades are subject to commercial risks for which eBuySugar shall not be responsible.',
                ],
            },
        ],
    },
];

function AccordionSection({ section, color, isLast }) {
    const [open, setOpen] = useState(false);
    return (
        <div className={`${isLast ? '' : 'border-b border-gray-100'}`}>
            <button onClick={() => setOpen(v => !v)}
                className="w-full flex items-center justify-between px-4 py-3.5 text-left">
                <span className="font-bold text-sm text-gray-800 pr-3 leading-snug">{section.title}</span>
                <motion.div animate={{ rotate: open ? 180 : 0 }} transition={{ duration: 0.2 }} className="flex-shrink-0">
                    <ChevronDown size={15} style={{ color }} />
                </motion.div>
            </button>
            <AnimatePresence initial={false}>
                {open && (
                    <motion.div key="body"
                        initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.25, ease: 'easeInOut' }}
                        className="overflow-hidden">
                        <div className={`px-4 pb-4 ${section.isContact ? '' : ''}`}>
                            {section.isContact ? (
                                <div className="rounded-xl px-4 py-4 border"
                                    style={{ background: '#f5f3ff', borderColor: '#ddd6fe' }}>
                                    {section.content.map((line, i) => (
                                        <p key={i} className="text-sm text-gray-700 leading-relaxed font-medium"
                                            style={{ fontWeight: i === 0 ? 800 : i === section.content.length - 1 ? 500 : 600, color: i === 0 ? '#7c3aed' : '#374151', marginBottom: i < section.content.length - 1 ? 4 : 0 }}>
                                            {line}
                                        </p>
                                    ))}
                                </div>
                            ) : (
                                <div className="flex flex-col gap-2.5">
                                    {section.content.map((para, i) => (
                                        <p key={i} className="text-[13px] text-gray-600 leading-relaxed font-medium"
                                            style={{ lineHeight: 1.75 }}>
                                            {para}
                                        </p>
                                    ))}
                                </div>
                            )}
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
}

export default function TermsPage() {
    const [openPart, setOpenPart] = useState('terms');

    return (
        <AppLayout title="Terms of Use" showBack>
            <div className="px-4 pt-3 pb-10">

                {/* Header banner */}
                <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}
                    className="rounded-2xl p-4 mb-4 relative overflow-hidden"
                    style={{ background: 'linear-gradient(135deg,#ef3837,#d92300)', boxShadow: '0 4px 16px rgba(239,56,55,0.28)' }}>
                    <div className="absolute -right-4 -top-4 w-20 h-20 rounded-full bg-white/10" />
                    <div className="absolute right-6 bottom-0 w-12 h-12 rounded-full bg-white/10" />
                    <div className="relative">
                        <p className="text-white/70 text-[10px] font-extrabold uppercase tracking-widest mb-1">eBuySugar</p>
                        <p className="text-white text-[17px] font-black leading-tight mb-1">Terms of Use</p>
                        <p className="text-white/60 text-xs font-semibold">JK India eAgriTech Ltd. &nbsp;·&nbsp; Last updated July 2025</p>
                    </div>
                </motion.div>

                {/* Part tabs */}
                <div className="flex gap-2 mb-4 overflow-x-auto pb-0.5" style={{ scrollbarWidth: 'none' }}>
                    {PARTS.map(part => {
                        const isActive = openPart === part.id;
                        return (
                            <button key={part.id} onClick={() => setOpenPart(part.id)}
                                className="flex-shrink-0 flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-extrabold transition-all border"
                                style={{
                                    background: isActive ? part.color : 'white',
                                    color: isActive ? 'white' : part.color,
                                    borderColor: isActive ? part.color : `${part.color}40`,
                                    boxShadow: isActive ? `0 4px 14px ${part.color}35` : 'none',
                                }}>
                                <span className="text-[10px] font-bold opacity-70">{part.part}</span>
                                {part.title}
                            </button>
                        );
                    })}
                </div>

                {/* Part content */}
                {PARTS.map(part => {
                    if (part.id !== openPart) return null;
                    const Icon = part.icon;
                    return (
                        <motion.div key={part.id} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.22 }}>
                            {/* Part header */}
                            <div className="flex items-center gap-3 mb-3 px-1">
                                <div className="w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0"
                                    style={{ background: `${part.color}15`, border: `1.5px solid ${part.color}30` }}>
                                    <Icon size={17} style={{ color: part.color }} strokeWidth={2.2} />
                                </div>
                                <div>
                                    <p className="text-[10px] font-extrabold uppercase tracking-wider" style={{ color: part.color }}>{part.part}</p>
                                    <p className="font-black text-[15px] text-gray-900 leading-tight">{part.title}</p>
                                </div>
                            </div>

                            {/* Accordion sections */}
                            <div className="bg-white rounded-2xl overflow-hidden border border-gray-100"
                                style={{ boxShadow: '0 2px 12px rgba(0,0,0,0.06)' }}>
                                {part.sections.map((section, i) => (
                                    <AccordionSection key={i} section={section} color={part.color}
                                        isLast={i === part.sections.length - 1} />
                                ))}
                            </div>
                        </motion.div>
                    );
                })}

                {/* Footer */}
                <div className="mt-6 text-center">
                    <p className="text-[11px] text-gray-400 font-medium leading-relaxed">
                        © {new Date().getFullYear()} All copyrights reserved with eBuySugar / JK India eAgriTech Ltd., Kolhapur.
                    </p>
                </div>
            </div>
        </AppLayout>
    );
}
